name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install QPM
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/QuestPackageManager/QPM.CLI/releases/tags/v1.5.8 | python3 -c "import sys,json; data=json.load(sys.stdin); urls=[a['browser_download_url'] for a in data['assets'] if 'linux' in a['name'].lower()]; print(urls[0])")
          curl -L "$DOWNLOAD_URL" -o qpm.zip
          unzip qpm.zip -d qpm_extracted
          chmod +x qpm_extracted/qpm
          sudo mv qpm_extracted/qpm /usr/local/bin/qpm

      - name: Install Ninja & CMake
        run: sudo apt-get install -y ninja-build cmake

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Restore and Build
        run: |
          qpm config ndk-path "${{ steps.setup-ndk.outputs.ndk-path }}"
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          qpm restore
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DANDROID_NDK="${{ steps.setup-ndk.outputs.ndk-path }}" -B build
          cmake --build ./build

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: BaboonModMenu
          path: build/*.so
