name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install QPM
        run: |
          wget -O qpm https://github.com/QuestPackageManager/QPM.CLI/releases/latest/download/qpm-linux
          chmod +x qpm
          sudo mv qpm /usr/local/bin/qpm

      - name: Install NDK
        run: |
          wget -O ndk.zip https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip ndk.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r26d" >> $GITHUB_ENV

      - name: QPM Restore
        run: qpm restore

      - name: Install Ninja & CMake
        run: sudo apt-get install -y ninja-build cmake

      - name: Build
        run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build
          cmake --build ./build

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: BaboonModMenu
          path: build/*.so
